name: cava-resources
channels:
  - conda-forge
dependencies:
  - python==3.8
  - jupyter-book=0.12.1
  - xarray
  - ipykernel
  - intake
  - intake-xarray
  - cftime
  - matplotlib
  - hvplot
  - datashader
  - cmocean
  - ffmpeg
  - netcdf4
  - zarr
  - s3fs==2021.10.1
  - pip
  - panel
  - bokeh
  - pip:
    - sphinxcontrib-bibtex==2.2.0
    - git+https://github.com/ooi-data/ooi-harvester.git@main
