name: Deploy

on:
  push:
    paths:
      - 'book/**'
      - '.github/workflows/deploy.yaml'
      - 'environment.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: cava-resources
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: List conda packages
      run: |
        conda list

    - name: Build book
      shell: bash -l {0}
      run: |
        jupyter-book build book/

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: book/_build/html
        publish_branch: gh-pages
